const data = {
  status: "success",
  items: [
    {
      id: 1,
      title: "Hollow Knight",
      price: 30,
      image: require('./images/PC/PC01.png'),
      category: "Steam",
      cantidad: 1,
      sipnosis: "Hollow Knight es una aventura de acción clásica en 2D ambientada en un vasto mundo interconectado. Explora cavernas tortuosas, ciudades antiguas y páramos mortales. Combate contra criaturas corrompidas, haz nuevas amistades con extraños insectos y resuelve los antiguos misterios que yacen en el corazón del reino.",
    },
    {
      id: 2,
      title: "The Binding of Isaac",
      price: 15,
      image: require('./images/PC/PC02.png'),
      category: "Steam",
      cantidad: 1,
      sipnosis: "The Binding of Isaac(o simplemente Isaac) es un videojuego independiente de rol de acción y de mazmorras (dungeon crawler) roguelike, donde el jugador intenta escapar de su propia madre, la cual piensa que debe de sacrificar a su hijo para completar su tarea dada por Dios.",
    },
    {
      id: 3,
      title: "LIMBO",
      price: 20,
      image: require('./images/PC/PC03.jpg'),
      category: "Steam",
      cantidad: 1,
      sipnosis: " La premisa de LIMBO nos coloca en la “piel” de un pequeño niño que deberá recorrer distintos escenarios en busca de su hermana. Nuestro protagonista deberá desafiar y vencer las trampas, retos y enemigos que evitarán que cumplamos nuestro cometido.",
    },
    {
      id: 4,
      title: "Portal 2",
      price: 23,
      image: require('./images/PC/PC04.jpg'),
      category: "Steam",
      cantidad: 1,
      sipnosis: "Portal 2 es un juego de rompecabezas y humor negro en el que debes resolver desafiantes acertijos utilizando un dispositivo de portales mientras interactúas con personajes carismáticos y descubres oscuros secretos en las instalaciones de Aperture Science.",
    },
    {
      id: 5,
      title: "Sekiro: Shadows Die Twice",
      price: 203,
      image: require('./images/PC/PC05.png'),
      category: "Steam",
      cantidad: 1,
      sipnosis: "Shadows Die Twice es un intenso juego de acción y aventura en tercera persona que tiene lugar en el sangriento Japón del siglo XIV. Ponte en la piel de un guerrero caído en desgracia que ha sido rescatado de los brazos de la muerte y debe salvar a su maestro y vengarse de su archienemigo.",
    },
    {
      id: 6,
      title: "Terraria",
      price: 20,
      image: require('./images/PC/PC06.jpg'),
      category: "Steam",
      cantidad: 1,
      sipnosis: "Terraria es un videojuego de mundo abierto en 2D. Contiene elementos de construcción, exploración, aventura y combate, muy similar a juegos clásicos de la consola Super NES, como por ejemplo la serie Metroid, y a otras entregas no tan antiguas como Minecraft.",
    },
    {
      id: 7,
      title: "Wolfenstein: The New Order",
      price: 80,
      image: require('./images/PC/PC07.jpg'),
      category: "Steam",
      cantidad: 1,
      sipnosis: "Wolfenstein: The New Order plantea un escenario donde Alemania gana la Segunda Guerra Mundial. Desde el inicio, se muestran a los nazis como una potencia militar que domina el frente de guerra gracias a tecnología avanzada que obtuvo de forma misteriosa. Nuestro héroe, B. J. Blazkowicz, incursionará en la fortaleza del general alemán Deathshead para intentar detener sus planes y experimentos. ",
    },
    {
      id: 8,
      title: "Dying Light",
      price: 100,
      image: require('./images/PC/PC08.jpg'),
      category: "Steam",
      cantidad: 1,
      sipnosis: "Dying Light, es una aventura de acción en primera persona survival horror con un ciclo día-noche que determinará el nivel de agresividad de nuestros enemigos. ¡Sobrevive en una ciudad devastada por un virus de zombis! En tu misión secreta deberás tomar una decisión. ¿Serás fiel a tus superiores o salvarás a los supervivientes? Está en tus manos...",
    },
    {
      id: 9,
      title: "GTA V",
      price: 50,
      image: require('./images/PC/PC09.jpg'),
      category: "Steam",
      cantidad: 1,
      sipnosis: "Sumérgete en Los Santos, una ciudad ficticia inspirada en Los Ángeles, donde tres personajes, Michael, Franklin y Trevor, se embarcan en emocionantes delitos y aventuras. En este mundo abierto, podrás explorar una sociedad diversa, desde las colinas de Vinewood hasta los barrios bajos.",
    },
    {
      id: 10,
      title: "Half-life",
      price: 20,
      image: require('./images/PC/PC10.png'),
      category: "Steam",
      cantidad: 1,
      sipnosis: "Sumérgete en Los Santos, una ciudad ficticia inspirada en Los Ángeles, donde tres personajes, Michael, Franklin y Trevor, se embarcan en emocionantes delitos y aventuras. En este mundo abierto, podrás explorar una sociedad diversa, desde las colinas de Vinewood hasta los barrios bajos.",
    },
    {
      id: 11,
      title: "Elden Ring",
      price: 310,
      image: require('./images/PS/PS11.png'),
      category: "PlayStation 5",
      cantidad: 1,
      sipnosis: "Sumérgete en Los Santos, una ciudad ficticia inspirada en Los Ángeles, donde tres personajes, Michael, Franklin y Trevor, se embarcan en emocionantes delitos y aventuras. En este mundo abierto, podrás explorar una sociedad diversa, desde las colinas de Vinewood hasta los barrios bajos.",
    },
    {
      id: 12,
      title: "God of War: Ragnarok",
      price: 300,
      image: require('./images/PS/PS12.png'),
      category: "PlayStation 5",
      cantidad: 1,
      sipnosis: "Únete a Kratos y Atreus en una nueva aventura nórdica. Enfrenta a dioses, monstruos y peligros mortales mientras buscas prevenir el Ragnarok. Descubre una narrativa profunda y una relación entre padre e hijo.",
    },
    {
      id: 13,
      title: "Demon's Souls",
      price: 360,
      image: require('./images/PS/PS13.png'),
      category: "PlayStation 5",
      cantidad: 1,
      sipnosis: "Este remake del juego original presenta un mundo sombrío donde debes liberar Boletaria de la niebla demoníaca. Combate a criaturas aterradoras y desafiantes en una experiencia que estableció el género (Souls).",
    },
    {
      id: 14,
      title: "Resident Evil 4",
      price: 300,
      image: require('./images/PS/PS14.png'),
      category: "PlayStation 5",
      cantidad: 1,
      sipnosis: "Acompaña a Leon S. Kennedy en su misión de rescate en un pueblo rural plagado de plagas. Enfrenta a cultistas y horrores mutantes mientras buscas rescatar a la hija del presidente.",
    },
    {
      id: 15,
      title: "God of War",
      price: 100,
      image: require('./images/PS/PS15.png'),
      category: "PlayStation 4",
      cantidad: 1,
      sipnosis: "Únete a Kratos en su viaje por las tierras nórdicas. Atraviesa un mundo lleno de peligros mitológicos, lucha contra dioses y explora una emotiva relación padre-hijo.",
    },
    {
      id: 16,
      title: "Dark Souls III",
      price: 110,
      image: require('./images/PS/PS16.png'),
      category: "PlayStation 4",
      cantidad: 1,
      sipnosis: "Explora el mundo oscuro y decadente de Lothric mientras enfrentas a jefes colosales y criaturas aterradoras. Toma decisiones que afectan el destino del mundo.",
    },
    {
      id: 17,
      title: "Bloodborne",
      price: 60,
      image: require('./images/PS/PS17.png'),
      category: "PlayStation 4",
      cantidad: 1,
      sipnosis: "Sumérgete en la aterradora ciudad de Yharnam, asolada por una epidemia. Combate horrores góticos, desvela secretos y descubre una narrativa misteriosa.",
    },
    {
      id: 18,
      title: "Spider-Man: Miles Morales",
      price: 120,
      image: require('./images/PS/PS18.png'),
      category: "PlayStation 4",
      cantidad: 1,
      sipnosis: "En el papel de Miles Morales, lucha contra villanos mientras balanceas por la ciudad de Nueva York. Descubre tus habilidades arácnidas y protege la ciudad como el nuevo Spider-Man.",
    },
    {
      id: 19,
      title: "The Evil Within",
      price: 60,
      image: require('./images/PS/PS19.png'),
      category: "PlayStation 4",
      cantidad: 1,
      sipnosis: "Adéntrate en un mundo de pesadillas y horror psicológico como el detective Sebastian Castellanos. Al investigar un perturbador asesinato en un hospital, descubrirás una realidad retorcida poblada por criaturas espantosas. Tu mente se convertirá en tu peor enemigo mientras intentas sobrevivir.",
    },
    {
      id: 20,
      title: "The Evil Within 2",
      price: 65,
      image: require('./images/PS/PS20.png'),
      category: "PlayStation 4",
      cantidad: 1,
      sipnosis: "Continúa la historia de Sebastian mientras busca a su hija desaparecida en el aterrador mundo STEM. Enfréntate a horrores inimaginables, explora paisajes retorcidos y descubre oscuros secretos en esta secuela del juego de horror.",
    },
    {
      id: 21,
      title: "A Plague Tale: Requiem",
      price: 230,
      image: require('./images/XB/XB21.png'),
      category: "Xbox Series X",
      cantidad: 1,
      sipnosis: "Acompaña a Amicia y Hugo en una desgarradora historia de supervivencia en una Francia medieval asolada por la Peste Negra y en la que enjambres de ratas son una amenaza constante. En este juego de aventuras, enfrentarás peligros y resolverás acertijos para salvar a tu hermano.",
    },
    {
      id: 22,
      title: "Battlefield 2042",
      price: 250,
      image: require('./images/XB/XB22.png'),
      category: "Xbox Series X",
      cantidad: 1,
      sipnosis: "Sumérgete en la guerra del futuro en un conflicto global en escenarios enormes. Elije entre un variado elenco de especialistas, utiliza armamento avanzado y experimenta intensos combates en este shooter en primera persona.",
    },
    {
      id: 23,
      title: "The Callisto Protocol",
      price: 200,
      image: require('./images/XB/XB23.png'),
      category: "Xbox Series X",
      cantidad: 1,
      sipnosis: "Adéntrate en una prisión espacial en el año 2320, donde los prisioneros se enfrentan a horrores cósmicos. En este juego de terror, deberás luchar por tu vida y resolver misterios para sobrevivir.",
    },
    {
      id: 24,
      title: "Dead Space",
      price: 200,
      image: require('./images/XB/XB24.png'),
      category: "Xbox Series X",
      cantidad: 1,
      sipnosis: "Únete al ingeniero Isaac Clarke mientras lucha por sobrevivir en la nave espacial USG Ishimura, plagada de horrores alienígenas conocidos como Necromorphs. Con una narrativa tensa y una atmósfera espeluznante, este juego te mantendrá en vilo.",
    },
    {
      id: 25,
      title: "Forza Horizon 5",
      price: 210,
      image: require('./images/XB/XB25.png'),
      category: "Xbox Series X",
      cantidad: 1,
      sipnosis: "Disfruta de la adrenalina de las carreras en un mundo abierto y diverso inspirado en México. Con una variedad de vehículos y desafíos, explora paisajes deslumbrantes mientras compites contra otros pilotos.",
    },
    {
      id: 26,
      title: "Gears 5",
      price: 235,
      image: require('./images/XB/XB26.png'),
      category: "Xbox Series X",
      cantidad: 1,
      sipnosis: "Únete a Kait Diaz en su búsqueda de la verdad sobre su origen y enfrenta a la amenaza alienígena, los Locust. Este shooter en tercera persona ofrece intensas batallas y una narrativa cautivadora.",
    },
    {
      id: 27,
      title: "Hades",
      price: 150,
      image: require('./images/XB/XB27.png'),
      category: "Xbox Series X",
      cantidad: 1,
      sipnosis: "Embárcate en una odisea épica como Zagreus, el hijo del dios griego Hades, mientras intentas escapar del Inframundo. Lucha contra los siervos de Hades y forja alianzas divinas en esta experiencia roguelike.",
    },
    {
      id: 28,
      title: "Halo Infinite",
      price: 250,
      image: require('./images/XB/XB28.png'),
      category: "Xbox Series X",
      cantidad: 1,
      sipnosis: "El Jefe Maestro regresa en esta nueva entrega de la icónica saga. Enfréntate a la alianza Banished en un mundo abierto, descubre nuevos armamentos y explora emocionantes mundos alienígenas.",
    },
    {
      id: 29,
      title: "Starfield",
      price: 250,
      image: require('./images/XB/XB29.png'),
      category: "Xbox Series X",
      cantidad: 1,
      sipnosis: "Prepárate para explorar el espacio en este ambicioso juego de rol de ciencia ficción de los creadores de The Elder Scrolls y Fallout. Aventúrate en un sistema estelar sin explorar y descubre secretos cósmicos.",
    },
    {
      id: 30,
      title: "The Witcher: Wild Hunt",
      price: 240,
      image: require('./images/XB/XB30.png'),
      category: "Xbox Series X",
      cantidad: 1,
      sipnosis: "Encarna a Geralt de Rivia, un cazador de monstruos y brujo, en un mundo lleno de criaturas fantásticas, conflictos políticos y elecciones morales. Busca a Ciri y enfrenta una amenaza cósmica en esta épica aventura de rol.",
    },
  ],
};

export default data;